# coding: utf-8

"""
    Buxfer API

    Buxfer API based on their website.  -----------  Attention! --------------  THIS IS NOT AN OFFICIAL BUXFER.COM API  ----------- Attention! --------------  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: robbiegal@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.request_token import RequestToken  # noqa: E501
from swagger_client.rest import ApiException


class TestRequestToken(unittest.TestCase):
    """RequestToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestToken(self):
        """Test RequestToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.request_token.RequestToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
